apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: php-site-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/djkaz/argocd-php-lab.git
    targetRevision: HEAD
    path: charts/php-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
